### ISSUE TITLE
Error at refresh

### ISSUE THREAD

**Issue by Mihaiii** [StarcounterApps/Website#175]
1. Delete database
2. Run SignIn app @ https://github.com/StarcounterApps/SignIn/commit/a46d297a1393b64a2002e8c9ed8da177c6a748a4 (current latest version on `develop`)
3. Run Website app @ https://github.com/StarcounterApps/Website/commit/ac1b85133e67f8da187cb2767d83d59272e4d2f6 (current latest version on `develop`)
4. Go to `http://localhost:8080/signin/generateadminuser`
5. Go to `http://localhost:8080/websiteeditor` and Sign In.
6. Hit refresh
7. You'll get 
```
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: Can not find referenced Html file: "/websiteprovider/surfaces/DefaultSurface.html"
   at Starcounter.HtmlFromJsonProvider.ProvideFromFilePath[T](String filePath) in C:\TeamCity\BuildAgent\work\sc-7269\Level1\src\Starcounter\Middleware\HtmlFromJsonProvider.cs:line 58
   at Starcounter.HtmlFromJsonProvider.Invoke(MimeProviderContext context, Action next) in C:\TeamCity\BuildAgent\work\sc-7269\Level1\src\Starcounter\Middleware\HtmlFromJsonProvider.cs:line 52
   at Starcounter.MimeProviderMap.InvokeAll(MimeType type, Request request, IResource resource) in C:\TeamCity\BuildAgent\work\sc-7269\Level1\src\Starcounter\Middleware\MimeProviderMap.cs:line 126
   at Starcounter.Internal.ResourceMimeConverter.TryConvert(Request request, IResource resource, String mimeTypeStr, String& resultingMimeType) in C:\TeamCity\BuildAgent\work\sc-7269\Level1\src\Starcounter.Apps.JsonPatch\BuiltInRestHandlers\ResourceMimeConverter.cs:line 56
   at Starcounter.Internal.ResourceMimeConverter.Convert(Request request, Response response, String& resultingMimeType) in C:\TeamCity\BuildAgent\work\sc-7269\Level1\src\Starcounter.Apps.JsonPatch\BuiltInRestHandlers\ResourceMimeConverter.cs:line 46
   at Starcounter.Response.ConvertResource(Request req) in C:\TeamCity\BuildAgent\work\sc-7269\Level1\src\Starcounter.Internal\Http\Response.cs:line 765
   at Starcounter.Response.ConstructFromFields(Request req, Byte[] givenBuffer) in C:\TeamCity\BuildAgent\work\sc-7269\Level1\src\Starcounter.Internal\Http\Response.cs:line 821
   at Starcounter.Request.SendResponse(Response resp, Byte[] serializationBuf) in C:\TeamCity\BuildAgent\work\sc-7269\Level1\src\Starcounter.Internal\Http\Request.cs:line 1243
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in C:\TeamCity\BuildAgent\work\sc-7269\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 819
ParamName=Can not find referenced Html file: "/websiteprovider/surfaces/DefaultSurface.html"
HResult=-2146233086

More information about this error may be available in the server error log.
```

Now you don't have any apps running so:

8. Run SignIn app
9. Run Website app
10. Run SampleWebsiteTheme app
11. Go to `http://localhost:8080/websiteeditor`.
12. Sign out from within Websiteeditor
13. Sign in from within Websiteeditor.
14. Hit refresh.
15. You still get the error from point 7 even though SampleWebsiteTheme was running (and also all the apps will stop running).

SC version: 2.3.1.6981

**Comment by Mihaiii** [comment]
Closing as is another issue ( #177 ) was open after it and it seems that is the same one.
