### ISSUE TITLE
NullReferenceException when Pinning Rule refers to a static html

### ISSUE THREAD

**Issue by joozek78** [StarcounterApps/Website#56]
### Steps to reproduce

1. Create a pinning rule that has its Pin URI set to a static html file (can be `/Website/templates/DefaultTemplate.html`)
1. Go to a URL that uses this rule

### Expected result

It would be enough if an informative error would be displayed. Example:

> Pinning Rules have to refer to a URL resolving to a Json. URL "/Website/templates/DefaultTemplate.html" does not load a Json instance. If you want to have a Pinning Rule with a static HTML consider using the Content app.

It would probably be even better to automatically wrap static HTMLs with Json instance (`new Json {"Html"= htmlUrl}`)

### Actual result

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at WebsiteProvider.ContentHandlers.UpdateTemplateSections(String requestUri, Response response, WebTemplatePage content, WebUrl url) in C:\Users\joozek\dev\website\src\WebsiteProvider\Api\ContentHandlers.cs:line 186
   at WebsiteProvider.ContentHandlers.<Register>b__3_2(String requestUri) in C:\Users\joozek\dev\website\src\WebsiteProvider\Api\ContentHandlers.cs:line 102
   at lambda_method(Closure , Request , IntPtr , IntPtr )
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in C:\TeamCity\BuildAgent\work\sc-3291\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 341
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in C:\TeamCity\BuildAgent\work\sc-3291\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 98
   at Starcounter.Rest.UriManagedHandlersCodegen.RunUriMatcherAndCallHandler(String methodSpaceUriSpace, String methodSpaceUriSpaceLower, Request req, UInt16 portNumber, Response& resp) in C:\TeamCity\BuildAgent\work\sc-3291\Level1\src\Starcounter.Rest\UriManagedHandlersCodegen.cs:line 1133
   at Starcounter.Self.DoSelfCall(UInt16 portNumber, String method, String relativeUri, Dictionary`2 headersDictionary, String body, Byte[] bodyBytes, HandlerOptions handlerOptions, Request req) in C:\TeamCity\BuildAgent\work\sc-3291\Level1\src\Starcounter.Internal\Rest\Self.cs:line 397
   at Starcounter.Self.GET(String uri) in C:\TeamCity\BuildAgent\work\sc-3291\Level1\src\Starcounter.Internal\Rest\Self.cs:line 74
   at WebsiteProvider.ContentHandlers.<RegisterFilter>b__6_1(Request request, Response response) in C:\Users\joozek\dev\website\src\WebsiteProvider\Api\ContentHandlers.cs:line 138
   at Starcounter.Handle.RunResponseFilters(Request req, Response resp) in C:\TeamCity\BuildAgent\work\sc-3291\Level1\src\Starcounter.Internal\Handle.cs:line 560
   at Starcounter.Request.SendResponse(Response resp, Byte[] serializationBuf) in C:\TeamCity\BuildAgent\work\sc-3291\Level1\src\Starcounter.Internal\Http\Request.cs:line 1211
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in C:\TeamCity\BuildAgent\work\sc-3291\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 811
HResult=-2147467261

More information about this error may be available in the server error log.
```

##### Starcounter version

2.3.0.5851

##### Involved apps' version

StarcounterApps/Website@0b1fa612cb1445d27f072a874b07b573fd9f2e16

**Comment by PatrykSzwer** [comment]
Closing since exception no longer occurs. Right now if static html path URI or any wrong uri is provided there is simply just no response for that and nothing is displayed. 

Discussed with @joozek78
